const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  CREATE_DASHBOARD_REQUEST: 'CREATE_DASHBOARD_REQUEST',
  CREATE_DASHBOARD_SUCCESS: 'CREATE_DASHBOARD_SUCCESS',
  CREATE_DASHBOARD_FAILURE: 'CREATE_DASHBOARD_FAILURE',
  GET_DASHBOARDS_REQUEST: 'GET_DASHBOARDS_REQUEST',
  GET_DASHBOARDS_SUCCESS: 'GET_DASHBOARDS_SUCCESS',
  GET_DASHBOARDS_FAILURE: 'GET_DASHBOARDS_FAILURE',
  GET_DEFAULT_DASHBOARD_REQUEST: 'GET_DEFAULT_DASHBOARD_REQUEST',
  GET_DEFAULT_DASHBOARD_SUCCESS: 'GET_DEFAULT_DASHBOARD_SUCCESS',
  GET_DEFAULT_DASHBOARD_FAILURE: 'GET_DEFAULT_DASHBOARD_FAILURE',
  CHANGE_DASHBOARD: 'CHANGE_DASHBOARD',
  ADD_CREATED_DASHBOARD: 'ADD_CREATED_DASHBOARD',
  PICK_COLOR: 'PICK_COLOR'
}

export default actionTypes;